# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rolexx/Desktop/c++/producer_consumer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rolexx/Desktop/c++/producer_consumer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rolexx/Desktop/c++/producer_consumer/CMakeFiles /home/rolexx/Desktop/c++/producer_consumer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rolexx/Desktop/c++/producer_consumer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named queue-server

# Build rule for target.
queue-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 queue-server
.PHONY : queue-server

# fast build rule for target.
queue-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/build
.PHONY : queue-server/fast

src/ClientHandler.o: src/ClientHandler.cpp.o
.PHONY : src/ClientHandler.o

# target to build an object file
src/ClientHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/ClientHandler.cpp.o
.PHONY : src/ClientHandler.cpp.o

src/ClientHandler.i: src/ClientHandler.cpp.i
.PHONY : src/ClientHandler.i

# target to preprocess a source file
src/ClientHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/ClientHandler.cpp.i
.PHONY : src/ClientHandler.cpp.i

src/ClientHandler.s: src/ClientHandler.cpp.s
.PHONY : src/ClientHandler.s

# target to generate assembly for a file
src/ClientHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/ClientHandler.cpp.s
.PHONY : src/ClientHandler.cpp.s

src/DelimitedProtocol.o: src/DelimitedProtocol.cpp.o
.PHONY : src/DelimitedProtocol.o

# target to build an object file
src/DelimitedProtocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/DelimitedProtocol.cpp.o
.PHONY : src/DelimitedProtocol.cpp.o

src/DelimitedProtocol.i: src/DelimitedProtocol.cpp.i
.PHONY : src/DelimitedProtocol.i

# target to preprocess a source file
src/DelimitedProtocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/DelimitedProtocol.cpp.i
.PHONY : src/DelimitedProtocol.cpp.i

src/DelimitedProtocol.s: src/DelimitedProtocol.cpp.s
.PHONY : src/DelimitedProtocol.s

# target to generate assembly for a file
src/DelimitedProtocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/DelimitedProtocol.cpp.s
.PHONY : src/DelimitedProtocol.cpp.s

src/Server.o: src/Server.cpp.o
.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i
.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s
.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queue-server.dir/build.make CMakeFiles/queue-server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... queue-server"
	@echo "... src/ClientHandler.o"
	@echo "... src/ClientHandler.i"
	@echo "... src/ClientHandler.s"
	@echo "... src/DelimitedProtocol.o"
	@echo "... src/DelimitedProtocol.i"
	@echo "... src/DelimitedProtocol.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

